### ISSUE TITLE
unusual halpha luminosity

### ISSUE THREAD

**Issue by changhoonhahn** [IQcollaboratory/galpopFM#11]
Halpha luminosity measured from `measure_obs.L_Ha` for SIMBA are in the right ballpark but the distribution is quite different than the SDSS/NSA. 

@TStarkenburg could you double check the code? The test script is in `run/_measure_obs.py`. 

![simba ha_hb](https://user-images.githubusercontent.com/1895640/74257807-953e5000-4cb2-11ea-813f-832ce4ccf365.png)

**Comment by TStarkenburg** [comment]
See my answer to thread #13. I will double check the code anyway, but could you remake the figure and compare with mine?

**Comment by changhoonhahn** [comment]
New SIMBA SEDs address the issue!

![image](https://user-images.githubusercontent.com/1895640/76041468-fdc1cb00-5f06-11ea-9063-7a42db112784.png)
