### ISSUE TITLE
need to improve data sharing

### ISSUE THREAD

**Issue by changhoonhahn** [IQcollaboratory/galpopFM#13]
@TStarkenburg I think we need to come up with a better way of sharing the SED, galaxy properties, etc than the flatiron links. 

I tried downloading the updated SIMBA data, but it did not fix the blob in the Halpha luminosity. Could it be that the cca link doesn't give access to the updated data? 

![simba ha_hb](https://user-images.githubusercontent.com/1895640/74361094-81aeea00-4d83-11ea-9ed4-8abb7708149a.png)

**Comment by TStarkenburg** [comment]
My Ha-luminosity-based SFR w/o dust closely matches the instantaneous SFR so error in the spectra I had is corrected. 
I am working on getting all the spectra in the shared folder. And will check the code.
<img width="416" alt="Screen Shot 2020-02-27 at 4 36 23 PM" src="https://user-images.githubusercontent.com/7421403/75493467-8d073580-597f-11ea-8367-eb91e8f387f2.png">

**Comment by TStarkenburg** [comment]
The newest spectra are now all in the Drive. Although SIMBA still is on the high side there is not a separate cluster anymore, and it is similar in maximum Ha luminosity reached as some of the other sims. So I'm closing this issue.
[Catalogs_HaHb_noDust_scatter.pdf](https://github.com/IQcollaboratory/galpopFM/files/4269439/Catalogs_HaHb_noDust_scatter.pdf)
[Catalogs_HaHb_noDust.pdf](https://github.com/IQcollaboratory/galpopFM/files/4269440/Catalogs_HaHb_noDust.pdf)
