### ISSUE TITLE
FUV-NUV locus in SDSS

### ISSUE THREAD

**Issue by changhoonhahn** [IQcollaboratory/galpopFM#14]
Below is a plot that compares the Balmer ratio and UV color as a function of Mr for SDSS and our SIMBA + dust FM. In the right panel, it seems that a substantial fraction of SDSS galaxies have FUV-NUV ~ 2.0 (red circle). Does anyone know why we see that flat feature? 

![simba explore_distance copy](https://user-images.githubusercontent.com/1895640/74451383-c3e83200-4e3c-11ea-9134-a6f19234a67e.png)

**Comment by changhoonhahn** [comment]
Looked into this in more detail in [notebook](https://github.com/IQcollaboratory/galpopFM/blob/bb812273f9a25a9e2239b34e85f7ecb0a5da264c/nb/sdss_fuv_nuv_locus.ipynb) and bb812273f9a25a9e2239b34e85f7ecb0a5da264c . 

FUV-NUV histogram emphasizes the unusual color
![image](https://user-images.githubusercontent.com/1895640/80020498-027a1880-848e-11ea-8621-aaeb512fde50.png)

They're mostly quiescent
![image](https://user-images.githubusercontent.com/1895640/80020508-060d9f80-848e-11ea-84a9-fdf6d6ea99b1.png)

FUV and NUV seem reasonable
![image](https://user-images.githubusercontent.com/1895640/80020512-086ff980-848e-11ea-86d5-2fbb7f87da33.png)

**Comment by TStarkenburg** [comment]
Sorry, I did expect these to be quiescent galaxies. And I've always understood that the explanation for this being flat in FUV-NUV, or a linear scaling between the two, is that there is still UV light coming from an old stellar population so the UV spectrum has a ~fixed slope if there are no young stars. However, I'm a bit puzzled by the location in FUV-NUV being quite different than the quiescent galaxies in the simulations... Dust may have some effect here though.

**Comment by changhoonhahn** [comment]
@TStarkenburg I see. So this is not something I should be concerned about --- great 😄 

As for the different FUV-NUV location in the sims, I'm not sure about that. In the figure I made for checking SFR=0 galaxies, there does seem to be a handful of galaxies with FUV-NUV ~1.8 at Mr~-20.  

![image](https://user-images.githubusercontent.com/1895640/80032944-c69c7e80-84a0-11ea-967d-5950713da507.png)

Since this is no longer a concern, I'm closing this issue.
