### ISSUE TITLE
possible inconsistency in inclination

### ISSUE THREAD

**Issue by changhoonhahn** [IQcollaboratory/galpopFM#2]
@TStarkenburg 

In Somerville+1999 the inclination dependence of the slab model depends on sec(incl) not cos(incl) (see Eq.14 of Somerville+1999). In `galpop.dustfm.slab_calzetti` and in the code you sent me, cos is used. Can you check this for consistency?

**Comment by changhoonhahn** [comment]
@TStarkenburg I realized I divided by sec rather than adding by it. I've fixed this bug in the latest update (#20). I've also implemented a tau_V > 0 limit, which I think is sensible. Could you sanity check these changes? Thanks!

**Comment by TStarkenburg** [comment]
Somerville+1999 has tau*sec(i) while the slab model (and the code I sent you) has tau/cos(i) from Somerville+2012. As sec(i) = 1/cos(i) this is the same thing. The current version is correct. And having TauV >=0 is also ok.
