### ISSUE TITLE
noise model

### ISSUE THREAD

**Issue by changhoonhahn** [IQcollaboratory/galpopFM#3]
@clairemackay 

Would it be possible to put even a rudimentary version of the noise model within the module `galpopfm.noiseFM` that I can include in the forward model?

**Comment by clairemackay** [comment]
definitely! what would you like the parameters to be? my current version uses g-r and apparent r mag, but I could do something really simple with stellar mass as another option.

**Comment by changhoonhahn** [comment]
For now, I think the simplest thing (stellar mass dependence) would work. 

Or even just a constant noise model...

**Comment by changhoonhahn** [comment]
implemented a very simple noise model in based on [nb/noise_model.ipynb](https://github.com/IQcollaboratory/galpopFM/blob/9f987d204735fd3286ccdcf945ccbde2038012bf/nb/noise_model.ipynb)
