### ISSUE TITLE
blue UV color galaxies

### ISSUE THREAD

**Issue by changhoonhahn** [IQcollaboratory/galpopFM#39]
Whether there is dust attenuation or not there's a group of galaxies that have very blue UV colors.

![image](https://user-images.githubusercontent.com/1895640/77599374-adb0a580-6ec1-11ea-804c-6d12631b063c.png)

![image](https://user-images.githubusercontent.com/1895640/77599379-b0ab9600-6ec1-11ea-93c0-210823e7bb98.png)

 These galaxies seem unaffected by changes in the DEM. What type of galaxies are they and why are they unaffected?

**Comment by changhoonhahn** [comment]
Most of the galaxies with high FUV-NUV are quiescent galaxies with SFR = 0. This seems to suggest that resolution effects impact the SFH, which then propagate to our observable. @TStarkenburg what do you think?

It may be possible to test the impact of this by sampling the SFH from the [0, SFR resolution] for the time bins with SFR = 0.  

(see [nb/blue_uv_galaxies.ipynb](https://github.com/IQcollaboratory/galpopFM/blob/bcc069a4703cf7ec4051a2cd4d8b6e56c17bee0c/nb/blue_uv_galaxies.ipynb))

**Comment by TStarkenburg** [comment]
Just to record our conclusions on this: the simulations predict too many quiescent galaxies (this can also be seen in other papers). Many of these SFR = 0 galaxies have no current SFR (instantaneous SFR doesn't have the resolution issues noted above), no recent SFR, and no gas. We will add flexibility to the DEM for the SFR = 0 galaxies.
