### ISSUE TITLE
SDSS A_V measurements

### ISSUE THREAD

**Issue by changhoonhahn** [IQcollaboratory/galpopFM#41]
We need A_V measurements for SDSS in order to: 
- sample A_V directly for SFR = 0 population
- implement non-slab model that uses the A_V distribution

**Comment by TStarkenburg** [comment]
![SDSS_Av](https://user-images.githubusercontent.com/7421403/79980434-b49ee980-8468-11ea-9c09-9e1a6f430649.png)
SDSS galaxies. Classification is from Brinchmann+2004. TauV is from their continuum fit (best fit from three metallicity BC01 models), so does not depend on the spectra. A_V = TauV * 1.086

**Comment by changhoonhahn** [comment]
Based on these SDSS distributions, I've settled on sampling A_V from a truncated normal distribution for now (see [notebook](https://github.com/IQcollaboratory/galpopFM/blob/7fd01fe6461a90294ac9b4c68549dac14b43db57/nb/slab_model_replace.ipynb) and 7fd01fe6461a90294ac9b4c68549dac14b43db57). 

Closing this issue for now.
