### ISSUE TITLE
TNG stellar mass function

### ISSUE THREAD

**Issue by changhoonhahn** [IQcollaboratory/galpopFM#46]
Here's a comparison of the SMFs and SFR-M* relations of the three simulations. 
<img width="1036" alt="Screen Shot 2020-10-22 at 12 15 33 PM" src="https://user-images.githubusercontent.com/1895640/96900604-49a68d80-1460-11eb-8bbf-522348aa571c.png">
The TNG SMF has an unexpected discrepancy with the rest of the simulations and SDSS observations.

I'm using 75^3 for the volume and the file `IQSFSdata_TNG_99-corrected.txt` for galaxy properties.

**Comment by TStarkenburg** [comment]
TNG volume: 110.7 Mpc. Could that be it?

**Comment by TStarkenburg** [comment]
From the papers: TNG from Pillepich+2018, SIMBA from Dave+2019, EAGLE from Schaye+2015
<img width="762" alt="Screen Shot 2020-10-22 at 12 16 11 PM" src="https://user-images.githubusercontent.com/7421403/96907153-79559580-1460-11eb-9786-a93d11f93889.png">
<img width="295" alt="Screen Shot 2020-07-15 at 2 12 35 PM" src="https://user-images.githubusercontent.com/7421403/96907302-ac982480-1460-11eb-8ccb-b230310663a1.png">
<img width="312" alt="Screen Shot 2020-07-09 at 7 31 28 PM" src="https://user-images.githubusercontent.com/7421403/96907349-bb7ed700-1460-11eb-8abb-b7604f982232.png">

**Comment by changhoonhahn** [comment]
Turns out I forgot to divide by dlogM for TNG. Everything looks normal now: 
![smf_m_sfr](https://user-images.githubusercontent.com/1895640/100181081-87576580-2ea7-11eb-9dd8-618120bb3b06.png)
